### ISSUE TITLE
Sběr dat od uživatelů

### ISSUE THREAD

**Issue by Lweek** [ZooHackaton2015/PalmOilChecker#2]
Zdravím ve spolek. Přihodil jsem do repozitáře **Jakuba Kvapila** @Jakub161 z Listari. Potřebovali bychom dovymyslet funkcionalitu. Jak nejlépe sbírat data. Už teď je jasné, že data si musíme nasbírat sami.

Máme dvě skupiny uživatelů. **Členové organizace** (důvěryhodní) a zbytek, tedy **náhodní uživatelé** (diskutabilní důvěryhodnost).

Za mne tu jsou tři scénáře:
1. aplikace bude dvojí (může se řešit autentifikací e.g. loginem), jedna pro členy a druhá pro veřejnost. Kdy sbírat data mohou jen členové. Otázkou je, jestli to nebude příliš pomalý sběr dat. I kdyby členové byli super aktivní, tak scanováním výrobků jeden po druhém na sebe mohou upoutat pozornost a čelit problémům s ochrankou.
2. aplikace nebude dvojí a validitu zadaných dat budeme nějak kontrolovat algorytmem. Např. deset shodných nasbíraných údajů = validní
3. aplikace nebude dvojí, ale uživatelé nebudou zadávat jestli je ve výrobku palmový olej nebo ne, ale pošlou fotku textu složení z obalu a někdo ze skupiny členů organizace vyhodnotí jestli tam je nebo není palmový olej. Dělat by to mohli kdykoliv pomocí webové nebo mobilní aplikace.

Nějaké další nápady? A případně jaký z těchto řešení vám přijde nejlepší a proč.

@Ttxman @Charon351 @ondrej-smola @humitch @rdpanek @RadarCZ

**Comment by ghost** [comment]
Ahoj
a co takhle kombinace 1 + 2 
nebo dokonce 1 + 2 + 3   zas tolik programování navíc to není a stejně se bude muset vytvořit nějaká administrace, nebo redukce programování na 1 + 3, nové výrobky přiskočí na začátku po chvíli používaní to už tak hektické nebude a pokud by editorům chodily notifikace o novém produktu a potřebě rozhodnout tak by to mohlo stačit.

**Comment by Jakub161** [comment]
Ahoj vespolek,
mě osobně se líbí hlavně 2, jelikož mi přijde, že by to mohl být poměrně
spolehlivý systém. U té 3 se obávám, že vyhodnocování fotografií bude
časově poměrně náročné a vyžádalo by si asi práci několika lidí. Zas na
druhou stranu, máme spoustu dobrovolníků, které nemáme jak zaúkolovat,
takže by to vlastně možná i šlo takhle.

Dne 9. prosince 2015 15:11 Karel Blavka notifications@github.com
napsal(a):

**Comment by ghost** [comment]
Ano, ale pokud existuje komunita "důvěryhodných" uživatelů tak jí to chce plně využít. Proto jsem psal kombinaci 1 + 2. Lze to udělat i tak, že se nebude počítat kolik shodných, ale score kde se započítá koeficient důvěryhodnosti uživatele. Takto by šlo po čase získat důvěryhodné i z řad mimo komunitu.

**Comment by Jakub161** [comment]
Komunita "důvěryhodných" uživatelů existuje, ale v zásadě by asi byla
poměrně malá. Věřím sice, že takových lidí reálně bude docela dost, ale
neznáme tolik lidí osobně a natolik dobře, abychom posoudili důvěryhodnost.
Bylo by skvělé, kdyby systém dokázal na základě nějakého způsobu získávat i
další důvěryhodné uživatele z řad veřejnosti!

Dne 10. prosince 2015 7:08 Karel Blavka notifications@github.com
napsal(a):

**Comment by ghost** [comment]
tak je to o statistice, čím více někdo pravdivě přispívá tím mu poroste, nejde o nic složitého
na jednom webu jsme měli něco podobného jen to bylo o hodnocení obrázků

**Comment by Jakub161** [comment]
Ahoj,
tak jsem se pokusil sepsat takový návrh toho, jak si myslím, že by se reálně dalo postupovat při tvorbě databáze  a získávání relevantních, ověřených dat. Myslím, že v situaci v jaké jsme bude nutné budovat kolektiv uživatelů postupně a ze začátku s omezenými počty uživatelů, abychom dokázali vše náležitě otestovat a ukočírovat. Nejsem si zcela jist číselnými odhady, ale mám o tom zhruba takovéto představy:

V tuto chvíli nemůžeme zajistit velkou skupinu dostatečně důvěryhodných lidí, kteří by byli schopni nám zasílat dostatečné množství informací. Proto navrhujeme řešení, při němž využijeme dvě skupiny uživatelů a provozu schopnost ověříme v alpha verzi aplikace s početně omezenou  komunitou. 

První skupina bude interní uzavřená skupina, která bude čítat max ?50? lidí, u kterých si můžeme být jistí pravdivostí informace, kterou nám zašlou. Tato kontrolní skupina bude vytvářet databázi potvrzených, pravdivých údajů, podle které se budou ověřovat informace od skupiny druhé.

Druhá skupina bude v alpha verzi také početně omezená (max. několik tisíc, nevím takhle z hlavy, jaký počet bude vhodný). Tato skupina bude složena z lidí, kteří problematiku PO řeší a jsou s  ní seznámeni. Tato skupina bude scanovat kódy z výrobků a přiřazovat k nim informaci obsahuje/neobsahuje PO. Podle shodnosti/rozdílnosti odpovědi s kontrolní skupinou bude danému zařízení, z nějž  budou informace přicházet přiřazována jakási míra kredibility (nevím zda na principu nějakého logaritmu...)

Data, která bude sbírat kontrolní skupina budou odvozena od těch, které začne načítat druhá skupina.  Správná, ověřená data tedy budou přicházet až následně po primárních datech. Zachování této posloupnosti není nutné, primární skupina může načítat libovolná data (tedy co jim zrovna přijde pod ruku).  Byl by ale užitečný jakýsi nástroj, který by umožnil kontrolní skupině sledovat, jaké výrobky  druhá skupina načítá a cíleně je vyhledávat a doplňovat kontrolní data, tak aby se daly oba sety dat spárovat. 

Doufám, že to alespoň trochu nastiňuje, jakou vizi s aplikací máme a že je to jakési vodítko pro to, jaké jsou podle nás reálné možnosti využití lidského potenciálu komunity kolem PO. Sem s nápady a připomínkami :)

**Comment by Lweek** [comment]
To zní jako plán. Pojďme se dohodnout na realizaci. Osobně v tuhle chvíli dovedu efektivně nabídnout pouze PHP + MySQL. To protože jsem celkem vytížený a jinou technologii aktuálně neovládám natolik abych ji byl schopný psát dostatečně svižně. Nicméně s PHP7 by to nemusel být takový problém. Je tu nekdo jiný schopný a ochotný se do toho pustit?

**Comment by Lweek** [comment]
Obsolete
